#!/usr/bin/env python

import sys
import diff_match_patch as dmp_module

try:
    from eduidconf_custom import conf
except ImportError:
    from eduidconf_defaults import conf


dmp = dmp_module.diff_match_patch()

origin = patched = sys.stdin.read()
filename = sys.argv[1]


settings = [c for c in dir(conf) if c.startswith('EDUIDCONF')]

for setting in settings:
    patched = patched.replace(setting, getattr(conf, setting))

if origin != patched:
    diff_o = dmp.patch_make(patched, origin)
    diff = dmp.patch_toText(diff_o)
    with open(filename + '.eduidpatch', 'w') as patch:
        patch.write(diff)

print(patched.rstrip(' \n'))
