#!/usr/bin/env python

import sys
import os
import diff_match_patch as dmp_module


dmp = dmp_module.diff_match_patch()

origin = sys.stdin.read()
filename = sys.argv[1] + '.eduidpatch'

if os.path.exists(filename):
    with open(filename) as patchfile:
        diff = patchfile.read()
        patches = dmp.patch_fromText(diff)
        patched, result = dmp.patch_apply(patches, origin)
        print(patched)
else:
    print(origin)
